"""add ordem_servico fields to contratos

Revision ID: 093478eaa62e
Revises: 74864da44091
Create Date: 2026-02-20 10:38:50.179440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '093478eaa62e'
down_revision: Union[str, None] = '74864da44091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contratos', sa.Column('numero_os', sa.String(length=50), nullable=True))
    op.add_column('contratos', sa.Column('data_os', sa.Date(), nullable=True))
    op.add_column('contratos', sa.Column('descricao_os', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contratos', 'descricao_os')
    op.drop_column('contratos', 'data_os')
    op.drop_column('contratos', 'numero_os')
    # ### end Alembic commands ###
