"""add nome to usuarios

Revision ID: 3aad7c89238f
Revises: e21a240aa6ba
Create Date: 2026-02-26 09:38:33.160217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3aad7c89238f'
down_revision: Union[str, None] = 'e21a240aa6ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('usuarios', 'senha_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('usuarios', 'perfil',
               existing_type=postgresql.ENUM('ADMIN', 'GESTOR', 'FINANCEIRO', 'AUDITOR', 'TI', name='perfil'),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('usuarios', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('usuarios', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('usuarios', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('ix_usuarios_email', table_name='usuarios')
    op.drop_index('ix_usuarios_id', table_name='usuarios')
    op.create_unique_constraint(None, 'usuarios', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.create_index('ix_usuarios_id', 'usuarios', ['id'], unique=False)
    op.create_index('ix_usuarios_email', 'usuarios', ['email'], unique=True)
    op.alter_column('usuarios', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('usuarios', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('usuarios', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('usuarios', 'perfil',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('ADMIN', 'GESTOR', 'FINANCEIRO', 'AUDITOR', 'TI', name='perfil'),
               nullable=False)
    op.alter_column('usuarios', 'senha_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('usuarios', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('usuarios', 'nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
