"""add gestor to contratos

Revision ID: 4e35a43ee67d
Revises: 093478eaa62e
Create Date: 2026-02-20 15:06:03.259277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e35a43ee67d'
down_revision: Union[str, None] = '093478eaa62e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contratos', sa.Column('gestor', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contratos', 'gestor')
    # ### end Alembic commands ###
