"""add missing fields to contrato_seguros

Revision ID: 55168c5f0e96
Revises: d490dc3a9b40
Create Date: 2026-02-23 08:04:43.221836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55168c5f0e96'
down_revision: Union[str, None] = 'd490dc3a9b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contrato_seguros', sa.Column('objeto_segurado', sa.Text(), nullable=True))
    op.add_column('contrato_seguros', sa.Column('possui_clausula_retomada', sa.Boolean(), nullable=True))
    op.add_column('contrato_seguros', sa.Column('observacoes', sa.Text(), nullable=True))
    op.alter_column('contrato_seguros', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('contrato_seguros', 'tomador_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('contrato_seguros_tomador_id_fkey', 'contrato_seguros', type_='foreignkey')
    op.drop_constraint('contrato_seguros_cliente_id_fkey', 'contrato_seguros', type_='foreignkey')
    op.create_foreign_key(None, 'contrato_seguros', 'empresas', ['cliente_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'contrato_seguros', 'empresas', ['tomador_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contrato_seguros', type_='foreignkey')
    op.drop_constraint(None, 'contrato_seguros', type_='foreignkey')
    op.create_foreign_key('contrato_seguros_cliente_id_fkey', 'contrato_seguros', 'empresas', ['cliente_id'], ['id'])
    op.create_foreign_key('contrato_seguros_tomador_id_fkey', 'contrato_seguros', 'empresas', ['tomador_id'], ['id'])
    op.alter_column('contrato_seguros', 'tomador_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('contrato_seguros', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('contrato_seguros', 'observacoes')
    op.drop_column('contrato_seguros', 'possui_clausula_retomada')
    op.drop_column('contrato_seguros', 'objeto_segurado')
    # ### end Alembic commands ###
