"""add valor_total to contratos

Revision ID: 679ab8c9aeba
Revises: 9e5ac85ced29
Create Date: 2026-02-19 18:22:35.756822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '679ab8c9aeba'
down_revision: Union[str, None] = '9e5ac85ced29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
