"""add nome to usuarios

Revision ID: b5f3b87a16df
Revises: 55168c5f0e96
Create Date: 2026-02-25 17:11:45.292554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5f3b87a16df'
down_revision: Union[str, None] = '55168c5f0e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alertas')
    op.add_column('usuarios', sa.Column('nome', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'nome')
    op.create_table('alertas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('mensagem', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('severidade', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('contrato_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('boletim_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('faturamento_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resolvido', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('resolvido_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('resolvido_por', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['boletim_id'], ['boletins_medicao.id'], name='alertas_boletim_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], name='alertas_contrato_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faturamento_id'], ['faturamentos.id'], name='alertas_faturamento_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolvido_por'], ['usuarios.id'], name='alertas_resolvido_por_fkey'),
    sa.PrimaryKeyConstraint('id', name='alertas_pkey')
    )
    # ### end Alembic commands ###
