"""update tipo_seguro enum with new values

Revision ID: d490dc3a9b40
Revises: 4e35a43ee67d
Create Date: 2026-02-20 16:36:59.811850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd490dc3a9b40'
down_revision: Union[str, None] = '4e35a43ee67d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.execute("ALTER TYPE tipo_seguro ADD VALUE 'LICITACAO'")
    op.execute("ALTER TYPE tipo_seguro ADD VALUE 'CONTRATO'")
    op.execute("ALTER TYPE tipo_seguro ADD VALUE 'RESPONSABILIDADE_CIVIL'")
    op.execute("ALTER TYPE tipo_seguro ADD VALUE 'RISCO_PROFISSIONAL'")
    op.execute("ALTER TYPE tipo_seguro ADD VALUE 'RISCO_ENGENHARIA'")
    op.execute("ALTER TYPE tipo_seguro ADD VALUE 'GARANTIA_CONTRATUAL_RETOMADA'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contrato_seguros', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
