"""add nome to usuarios

Revision ID: e21a240aa6ba
Revises: b5f3b87a16df
Create Date: 2026-02-26 08:06:58.205958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e21a240aa6ba'
down_revision: Union[str, None] = 'b5f3b87a16df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
